import { Course } from "../types/types";

export const allCsCourses: Course[] = [
  { courseNumber: 1, courseName: "Algebra", courseSemester: 1, courseCP: 5 },
  { courseNumber: 2, courseName: "Analysis", courseSemester: 1, courseCP: 5 },
  { courseNumber: 3, courseName: "Einführung in die Informatik", courseSemester: 1, courseCP: 5 },
  {
    courseNumber: 4,
    courseName: "Einführung in die Programmierung mit C und OOP Grundlagen",
    courseSemester: 1,
    courseCP: 15,
  },
  { courseNumber: 5, courseName: "BWL", courseSemester: 1, courseCP: 5 },
  { courseNumber: 6, courseName: "English", courseSemester: 1, courseCP: 5 },
  { courseNumber: 7, courseName: "Diskrete Mathematik", courseSemester: 2, courseCP: 5 },
  { courseNumber: 8, courseName: "Rechnerarchitekturen", courseSemester: 2, courseCP: 5 },
  {
    courseNumber: 9,
    courseName: "Algorithmen und Datenstrukturen",
    courseSemester: 2,
    courseCP: 5,
  },
  { courseNumber: 10, courseName: "Theoretische Informatik", courseSemester: 2, courseCP: 5 },
  {
    courseNumber: 11,
    courseName: "Software Engineering - Analysis",
    courseSemester: 3,
    courseCP: 5,
  },
  { courseNumber: 12, courseName: "Statistics", courseSemester: 3, courseCP: 5 },
  { courseNumber: 13, courseName: "OOP Programming in Java", courseSemester: 3, courseCP: 5 },
  { courseNumber: 14, courseName: "Databases", courseSemester: 3, courseCP: 5 },
  { courseNumber: 15, courseName: "Computer Networks", courseSemester: 3, courseCP: 5 },
  { courseNumber: 16, courseName: "Operating Systems", courseSemester: 3, courseCP: 5 },
  { courseNumber: 17, courseName: "Software Engineering - Design", courseSemester: 4, courseCP: 5 },
  { courseNumber: 18, courseName: "Real-Time Systems", courseSemester: 4, courseCP: 5 },
  { courseNumber: 19, courseName: "IT Security", courseSemester: 4, courseCP: 5 },
  { courseNumber: 20, courseName: "Distributed Systems", courseSemester: 4, courseCP: 5 },
  {
    courseNumber: 21,
    courseName: "Practical Computer Networks and Applications",
    courseSemester: 4,
    courseCP: 5,
  },
  { courseNumber: 22, courseName: "Programming Exercises", courseSemester: 4, courseCP: 5 },
  { courseNumber: 23, courseName: "Recht und Datenschutz", courseSemester: 1, courseCP: 5 },
  {
    courseNumber: 24,
    courseName: "Aktuelle Themen der Informatik",
    courseSemester: 5,
    courseCP: 5,
  },
  { courseNumber: 25, courseName: "Informatik-Projekt", courseSemester: 5, courseCP: 10 },
  { courseNumber: 26, courseName: "Wahlpflichtmodul", courseSemester: 5, courseCP: 5 },
  {
    courseNumber: 27,
    courseName: "Interdisziplinäres Studium Generale",
    courseSemester: 5,
    courseCP: 5,
  },
  { courseNumber: 28, courseName: "Praxisphase", courseSemester: 6, courseCP: 18 },
  {
    courseNumber: 29,
    courseName: "Bachelor-Arbeit mit Kolloquium",
    courseSemester: 6,
    courseCP: 12,
  },
];

export const allCsCourseNames: string[] = allCsCourses.map((course) => course.courseName);
